name: Build and push image to docker hub 🏗️ & 🚀

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      -
        name: Build and push bitcoind
        uses: docker/build-push-action@v2
        with:
          context: ./bitcoind/
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bitcoind-regtest:latest      
      -
        name: Build and push electrs
        uses: docker/build-push-action@v2
        with:
          context: ./electrs/
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/electrs:latest
