name: "[Build] electrs-regtest image"

on:
  push:
    branches:
      - main
    paths:
      - "electrs/**"
jobs:
  build-electrs-regtest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.TREZOR_BOT_USERNAME }}
          password: ${{ secrets.TREZOR_BOT_TOKEN }}
      -
        name: Build and push electrs-regtest image
        uses: docker/build-push-action@v2
        with:
          context: ./electrs/
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/electrs:latest
            ghcr.io/${{ github.repository_owner }}/electrs-regtest:latest
